### ISSUE TITLE
Use django-wiki from pip instead of from our custom wheel

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#335]
Back when our Django site was built, we needed django-wiki support in Django 2.2. Since the author did not have this available in the package that was available on PyPI, we decided to fork it and add the support ourselves.

The latest version of django-wiki, however, supports Django all the way up to Django 3. In other words, we no longer need to rely on this fork.

## Task
- [ ] Remove the wheels folder in `docker`, we no longer need to load this wheel. see 
      https://github.com/python-discord/site/tree/master/docker/wheels
- [ ] Change the Pipfile to get the latest version of django-wiki from PyPI
- [ ] Test the wiki functionality, to make sure we haven't broken anything. Fix any bugs that you find, 
        if possible.
- [ ] Open a pull request. In this pull request, make it clear that once the PR has been merged, 
      admins should delete our fork of `django-wiki`, which is no longer relevant and has nothing of 
      importance on it.

**Comment by MarkKoz** [comment]
Will use 0.5, which only supports up to Django 2.2, rather than the latest (0.6.x) because it's still a pre-release.
